### ISSUE TITLE
UFW not showing in output.

### ISSUE THREAD

**Issue by RyoshiKayo** [taylorthurlow/panda-motd#11]
### Bug description
UFW does not show in output when in config 

### Reproduction steps
```yaml
   service_status:
     enabled: true
     services:
       nginx: NGINX
       fail2ban: Fail2Ban
       snmpd: snmpd
       ufw: ufw
       php7.0-fpm: PHP7-FPM
```
```bash
$ panda-motd ~/.config/panda-motd.yaml
Services:
  fail2ban:   running
  nginx:      running
  php7.0-fpm: running
  snmpd:      running
...
```

### Expected behavior
```bash
$ panda-motd ~/.config/panda-motd.yaml
Services:
  fail2ban:   running
  nginx:      running
  php7.0-fpm: running
  snmpd:      running
  ufw:    running
```
### OS Information
 - OS: Debian 9

### Configuration File
https://gist.github.com/RyoshiKayo/34dafb49e8af391df6fd4b748c8c19e9
