### ISSUE TITLE
ssl_certificates error: Unable to find certificate expiration date

### ISSUE THREAD

**Issue by MarcelRobitaille** [taylorthurlow/panda-motd#37]
### Bug description
When I run the script, I get `ssl_certificates error: Unable to find certificate expiration date` in the ssl section

### Reproduction steps
1. configure an ssl certificate in the configuration file:
    ```
    ssl_certificates:
      enable: true
      certs:
        ...: /etc/letsencrypt/live/.../cert.pem
    ```
1. Run `panda-motd`

### Expected behavior
I expect `valid until <date>`

### Log file
`/var/log/panda-motd.error.log` exists but it's empty?

### OS Information
 - OS: Arch 5.10.14-arch1-1

### Configuration File
https://gist.github.com/MarcelRobitaille/19541379a55f19e21a8d8774a55662bf
